apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deployment
  labels:
    name: redis-app-deployment
    app: voting-app
spec:
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: voting-app
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
  replicas: 3
  selector:
    matchLabels:
      app: voting-app
