apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-deploy
  labels:
    app: back-end
spec:
  template:
    metadata:
      name: redis
      labels:
        app: redis
        tier: back-end
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
  replicas: 2
  selector:
    matchLabels:
      app: redis
      tier: back-end
