apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deploy
  labels:
    app: front-end
spec:
  template:
    metadata:
      name: guest-book
      labels:
        app: guest-book
        tier: front-end
    spec:
      containers:
        - name: guestbook
          image: kubernetes/guestbook:v2
          ports:
            - containerPort: 3000
  replicas: 3
  selector:
    matchLabels:
      app: guest-book
      tier: front-end
