apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  labels:
    app: front-end
spec:
  type: NodePort
  selector:
    app: guest-book
    tier: front-end
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30080
