apiVersion: v1
kind: Service
metadata:
  name: back-end-service
  labels:
    name: back-end-service
    app: guest-book
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    name: redis-pod
    app: guest-book
