apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  labels:
    name: front-end-service
    app: guest-book
spec:
  type: LoadBalancer
  ports:
    - targetPort: 3000
      port: 3000
  selector:
    name: front-end-pod
    app: guest-book
