apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  labels:
    name: front-end-deployment
    app: guest-book
spec:
  template:
    metadata:
      name: front-end-pod
      labels:
        name: front-end-pod
        app: guest-book
    spec:
      containers:
        - name: guestbook
          image: kubernetes/guestbook:v2
          ports:
            - containerPort: 3000
  replicas: 3
  selector:
    matchLabels:
      app: guest-book
